const fs = require('fs');
const path = require('path');

// ASCII Art templates
const asciiArt = {
  cat: `
   /\\   /\\
  (  . .)
   )   (
  (  v  )
 ^^  ^  ^^
`,
  dog: `
     /^-^\\
    /     \\
   (  o   o  )
    \\   <>  /
     ) --- (
    /       \\
   ( (  )  ) )
  (__(__)_)_)
`,
  heart: `
  ♥♥♥♥♥  ♥♥♥♥♥
♥♥     ♥♥     ♥♥
♥       ♥       ♥
 ♥             ♥
  ♥           ♥
   ♥         ♥
    ♥       ♥
     ♥     ♥
      ♥   ♥
       ♥ ♥
        ♥
`,
  star: `
      *
     ***
    *****
   *******
  *********
 ***********
*************
 ***********
  *********
   *******
    *****
     ***
      *
`,
  rocket: `
       /\\
      /  \\
     |    |
     |NASA|
     |    |
    /|    |\\
   / |____| \\
  /___________\\
 /_____________\\
     /~~~~~\\
    /~~~~~~~\\
   /_________\\
`,
  tree: `
        🌟
       /|\\
      /*|O\\
     /*/|\\*\\
    /X/O|*\\X\\
   /*/X/|\\X\\*\\
  /O/*/X|*\\O\\X\\
 /*/O/X/|\\X\\O\\*\\
/X/O/*/X|O\\*\\X\\O\\
        |X|
        |X|
`,
  castle: `
    🏰    🏰
    ||____||
    ||    ||
  __||____||__
 |  ________  |
 | |        | |
 | |   🚪   | |
 | |________| |
 |____________|
 |  🏰    🏰  |
 |____________|
`,
  computer: `
 ┌─────────────────┐
 │                 │
 │   > Hello_      │
 │   > World!      │
 │   > _           │
 │                 │
 └─────────────────┘
      │       │
   ┌──┴───────┴──┐
   │ ⚫  💿  🔊  │
   └─────────────┘
`
};

// Generate content for each markdown file
const generateMarkdownContent = (title, art, description) => {
  return `# ${title}

${description}

\`\`\`
${art}
\`\`\`

## About this ASCII Art

This ASCII art was generated as part of a collection of markdown files featuring various ASCII art designs.

Created with: **tmp-ai-ascii-art generator**

---
*Generated on: ${new Date().toISOString().split('T')[0]}*
`;
};

// File configurations
const files = [
  {
    filename: 'cat.md',
    title: 'ASCII Cat 🐱',
    art: asciiArt.cat,
    description: 'A cute ASCII art cat with whiskers and paws!'
  },
  {
    filename: 'dog.md',
    title: 'ASCII Dog 🐕',
    art: asciiArt.dog,
    description: 'A friendly ASCII art dog ready to play!'
  },
  {
    filename: 'heart.md',
    title: 'ASCII Heart ❤️',
    art: asciiArt.heart,
    description: 'A lovely ASCII art heart made with special characters.'
  },
  {
    filename: 'star.md',
    title: 'ASCII Star ⭐',
    art: asciiArt.star,
    description: 'A bright shining ASCII art star!'
  },
  {
    filename: 'rocket.md',
    title: 'ASCII Rocket 🚀',
    art: asciiArt.rocket,
    description: 'A NASA rocket ready for space exploration!'
  },
  {
    filename: 'tree.md',
    title: 'ASCII Christmas Tree 🎄',
    art: asciiArt.tree,
    description: 'A festive ASCII Christmas tree with a star on top!'
  },
  {
    filename: 'castle.md',
    title: 'ASCII Castle 🏰',
    art: asciiArt.castle,
    description: 'A magnificent ASCII art castle with towers and a door!'
  },
  {
    filename: 'computer.md',
    title: 'ASCII Computer 💻',
    art: asciiArt.computer,
    description: 'A retro ASCII art computer displaying "Hello World!"'
  }
];

// Create output directory
const outputDir = path.join(__dirname, 'ascii-art-files');
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir);
}

// Generate all markdown files
console.log('🎨 Generating ASCII Art Markdown Files...\n');

files.forEach((file, index) => {
  const content = generateMarkdownContent(file.title, file.art, file.description);
  const filepath = path.join(outputDir, file.filename);
  
  fs.writeFileSync(filepath, content);
  console.log(`✅ Generated: ${file.filename} - ${file.title}`);
});

// Generate an index file
const indexContent = `# ASCII Art Collection

Welcome to the ASCII Art Collection! This directory contains ${files.length} different ASCII art designs in markdown format.

## Available Files

${files.map((file, index) => 
  `${index + 1}. [${file.title}](${file.filename}) - ${file.description}`
).join('\n')}

## How to View

Simply open any of the markdown files above to view the ASCII art. Each file contains:
- The ASCII art in a code block for proper formatting
- A description of the artwork
- Generation timestamp

## Usage

You can use these files as:
- Documentation examples
- README decorations
- ASCII art references
- Template starting points

---
*Generated by tmp-ai-ascii-art generator on ${new Date().toISOString().split('T')[0]}*
`;

fs.writeFileSync(path.join(outputDir, 'README.md'), indexContent);
console.log('✅ Generated: README.md - Index file');

console.log(`\n🎉 Successfully generated ${files.length + 1} files in the '${outputDir}' directory!`);
console.log('\nFiles created:');
files.forEach(file => console.log(`  - ${file.filename}`));
console.log('  - README.md (index)');